### PR TITLE
Validate walltime results before uploading and error out if no bench found

### LINKED ISSUE #155: Graceful exit when there are no tests to run
If you `codspeed run` on a Go module with no benchmarks it will fail cryptically:

```
❯ codspeed run --mode walltime --skip-upload -- 'go test -bench=. ./...'

►►► Preparing the environment 
Tool already installed, skipping installation
Sudo privileges are required to continue. Please enter your password.
[sudo] password for pablo.baeyens: 
Environment ready

►►► Running the benchmarks 
[INFO  codspeed_go_runner] Discovered 0 packages
[INFO  codspeed_go_runner] Total benchmarks discovered: 0
[INFO  codspeed_go_runner] Parsed 0 raw results
Perf is enabled, but failed to detect benchmarks. If you wish to disable this warning, set CODSPEED_PERF_ENABLED=false
Error: Failed to copy log file
Error: No such file or directory (os error 2)
```

and if you `codspeed run` on a Go module with all benchmarks skipped it will panic:

```
❯ codspeed run --mode walltime --skip-upload -- 'go test -bench=. ./...'

►►► Preparing the environment 
Tool already installed, skipping installation
Environment ready

►►► Running the benchmarks 
[INFO  codspeed_go_runner] Discovered 1 packages
[INFO  codspeed_go_runner] Total benchmarks discovered: 1
[INFO  codspeed_go_runner] Found BenchmarkSkip                  in "profiles_test.go"
[INFO  codspeed_go_runner] Generating custom runner for package: xexporterhelper
[INFO  codspeed_go_runner] Building binary for package: xexporterhelper
PASS
[INFO  codspeed_go_runner] Parsed 0 raw results
  ⠂ Running the benchmarks...                                                                                                                                                                                                                                                   
thread 'main' panicked at src/run/runner/wall_time/perf/mod.rs:491:33:
called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The former I can identify with `go test ./... -list=Benchmark | grep -q Benchmark` but the latter I cannot: since benchmarks can be skipped in an arbitrary fashion I cannot determine statically what benchmarks would be run in the general case.

It would be useful if, when the runner parses 0 results, the error is a bit more descriptive and the exit code is 0 (or it is configurable to be zero).

### PR DESCRIPTION
**Pull request by GuillaumeLagrange**
Fixes #155

### CODE REVIEW

File: src/run/runner/wall_time/helpers.rs [hunk 1]
```diff
@@ -0,0 +1,272 @@
...
+    for entry in std::fs::read_dir(&results_dir)? {
+        let entry = entry?;
+        let path = entry.path();
+
+        // Only process JSON files
+        if path.extension().and_then(|s| s.to_str()) != Some("json") {
+            continue;
+        }
+
+        found_valid_results = true;
```
Comment (adriencaccia) [inline src/run/runner/wall_time/helpers.rs]: It makes more sense to move this statement at the end of the closure

File: src/run/runner/wall_time/helpers.rs [hunk 2]
```diff
@@ -0,0 +1,272 @@
...
+use runner_shared::walltime_results::WalltimeResults;
+use std::path::Path;
+
+fn add_error_explanation(error_details: &str) -> String {
+    format!(
+        "The command did not produce any CodSpeed result to process, did you run your benchmarks using a compatible CodSpeed integration?\n\
+        Check out https://codspeed.io/docs/benchmarks/overview for more information.\n\n\
+        Details: {error_details}"
+    )
+}
```
Comment (adriencaccia) [inline src/run/runner/wall_time/helpers.rs]: - [ ] Update the name of the function to something more explanatory, like "add_empty_results_error_explanation"

**Review by adriencaccia — APPROVED** [review]
